//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllInOneLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LauncherLanguageSetting {
            get {
                return ((int)(this["LauncherLanguageSetting"]));
            }
            set {
                this["LauncherLanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BFME1ResolutionSetting {
            get {
                return ((string)(this["BFME1ResolutionSetting"]));
            }
            set {
                this["BFME1ResolutionSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BFME1LanguageSetting {
            get {
                return ((int)(this["BFME1LanguageSetting"]));
            }
            set {
                this["BFME1LanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BFME2ResolutionSetting {
            get {
                return ((string)(this["BFME2ResolutionSetting"]));
            }
            set {
                this["BFME2ResolutionSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BFME2LanguageSetting {
            get {
                return ((int)(this["BFME2LanguageSetting"]));
            }
            set {
                this["BFME2LanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RotwkLanguageSetting {
            get {
                return ((int)(this["RotwkLanguageSetting"]));
            }
            set {
                this["RotwkLanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RotwkResolutionSetting {
            get {
                return ((string)(this["RotwkResolutionSetting"]));
            }
            set {
                this["RotwkResolutionSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BFME1GameInstalled {
            get {
                return ((bool)(this["BFME1GameInstalled"]));
            }
            set {
                this["BFME1GameInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BFME2GameInstalled {
            get {
                return ((bool)(this["BFME2GameInstalled"]));
            }
            set {
                this["BFME2GameInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RotwkGameInstalled {
            get {
                return ((bool)(this["RotwkGameInstalled"]));
            }
            set {
                this["RotwkGameInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWindowed {
            get {
                return ((bool)(this["IsWindowed"]));
            }
            set {
                this["IsWindowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>D:\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LibraryDrives {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LibraryDrives"]));
            }
            set {
                this["LibraryDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseLauncherToTray {
            get {
                return ((bool)(this["CloseLauncherToTray"]));
            }
            set {
                this["CloseLauncherToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BFME1GraphicAPISetting {
            get {
                return ((int)(this["BFME1GraphicAPISetting"]));
            }
            set {
                this["BFME1GraphicAPISetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BFME2GraphicAPISetting {
            get {
                return ((int)(this["BFME2GraphicAPISetting"]));
            }
            set {
                this["BFME2GraphicAPISetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RotwkGraphicAPISetting {
            get {
                return ((int)(this["RotwkGraphicAPISetting"]));
            }
            set {
                this["RotwkGraphicAPISetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateLauncherDesktopIcon {
            get {
                return ((bool)(this["CreateLauncherDesktopIcon"]));
            }
            set {
                this["CreateLauncherDesktopIcon"] = value;
            }
        }
    }
}
