//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatchLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayBackgroundMusic {
            get {
                return ((bool)(this["PlayBackgroundMusic"]));
            }
            set {
                this["PlayBackgroundMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackgroundMusicIcon {
            get {
                return ((int)(this["BackgroundMusicIcon"]));
            }
            set {
                this["BackgroundMusicIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string BackgroundMusicFile {
            get {
                return ((string)(this["BackgroundMusicFile"]));
            }
            set {
                this["BackgroundMusicFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EAXSupport {
            get {
                return ((bool)(this["EAXSupport"]));
            }
            set {
                this["EAXSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartGameWindowed {
            get {
                return ((bool)(this["StartGameWindowed"]));
            }
            set {
                this["StartGameWindowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBrutalAI {
            get {
                return ((bool)(this["UseBrutalAI"]));
            }
            set {
                this["UseBrutalAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameInstallPath {
            get {
                return ((string)(this["GameInstallPath"]));
            }
            set {
                this["GameInstallPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PatchVersionInstalled {
            get {
                return ((int)(this["PatchVersionInstalled"]));
            }
            set {
                this["PatchVersionInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGameInstalled {
            get {
                return ((bool)(this["IsGameInstalled"]));
            }
            set {
                this["IsGameInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch106Installed {
            get {
                return ((bool)(this["IsPatch106Installed"]));
            }
            set {
                this["IsPatch106Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch30Downloaded {
            get {
                return ((bool)(this["IsPatch30Downloaded"]));
            }
            set {
                this["IsPatch30Downloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch31Downloaded {
            get {
                return ((bool)(this["IsPatch31Downloaded"]));
            }
            set {
                this["IsPatch31Downloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectedOlderPatch {
            get {
                return ((bool)(this["SelectedOlderPatch"]));
            }
            set {
                this["SelectedOlderPatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch30Installed {
            get {
                return ((bool)(this["IsPatch30Installed"]));
            }
            set {
                this["IsPatch30Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch31Installed {
            get {
                return ((bool)(this["IsPatch31Installed"]));
            }
            set {
                this["IsPatch31Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSettingChanged {
            get {
                return ((bool)(this["IsSettingChanged"]));
            }
            set {
                this["IsSettingChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatchModsShown {
            get {
                return ((bool)(this["IsPatchModsShown"]));
            }
            set {
                this["IsPatchModsShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch106Downloaded {
            get {
                return ((bool)(this["IsPatch106Downloaded"]));
            }
            set {
                this["IsPatch106Downloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPatchesFirst {
            get {
                return ((bool)(this["ShowPatchesFirst"]));
            }
            set {
                this["ShowPatchesFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBetaChannel {
            get {
                return ((bool)(this["UseBetaChannel"]));
            }
            set {
                this["UseBetaChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BetaChannelVersion {
            get {
                return ((int)(this["BetaChannelVersion"]));
            }
            set {
                this["BetaChannelVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch32Installed {
            get {
                return ((bool)(this["IsPatch32Installed"]));
            }
            set {
                this["IsPatch32Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPatch32Downloaded {
            get {
                return ((bool)(this["IsPatch32Downloaded"]));
            }
            set {
                this["IsPatch32Downloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LatestPatchVersion {
            get {
                return ((int)(this["LatestPatchVersion"]));
            }
            set {
                this["LatestPatchVersion"] = value;
            }
        }
    }
}
