//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatchLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatchLauncher.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL GAME.
        /// </summary>
        internal static string BtnInstall_TextInstall {
            get {
                return ResourceManager.GetString("BtnInstall.TextInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH GAME.
        /// </summary>
        internal static string BtnInstall_TextLaunch {
            get {
                return ResourceManager.GetString("BtnInstall.TextLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta-Channel is activated! Deactivate in &quot;Launcher Options&quot; first and restart the Launcher to see Patches!.
        /// </summary>
        internal static string Info_BetaActivated {
            get {
                return ResourceManager.GetString("Info.BetaActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files and apply patch....
        /// </summary>
        internal static string Info_CopyFilesAndApplyPatch {
            get {
                return ResourceManager.GetString("Info.CopyFilesAndApplyPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for the one ring....
        /// </summary>
        internal static string Info_PleaseWait {
            get {
                return ResourceManager.GetString("Info.PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Setup....
        /// </summary>
        internal static string Info_PreparingSetup {
            get {
                return ResourceManager.GetString("Info.PreparingSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Update....
        /// </summary>
        internal static string Info_PreparingUpdate {
            get {
                return ResourceManager.GetString("Info.PreparingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Beta Update....
        /// </summary>
        internal static string Info_PreparingUpdateBeta {
            get {
                return ResourceManager.GetString("Info.PreparingUpdateBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Launcher restart is required for the settings to be applied. Do you want to restart now?.
        /// </summary>
        internal static string Msg_Restart_Text {
            get {
                return ResourceManager.GetString("Msg.Restart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Restart required.
        /// </summary>
        internal static string Msg_Restart_Title {
            get {
                return ResourceManager.GetString("Msg.Restart.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between faction music and default theme music.
        /// </summary>
        internal static string ToolTip_MusicSwitcher {
            get {
                return ResourceManager.GetString("ToolTip.MusicSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher is already running! Please Check TrayIcon or Taskmanager first..
        /// </summary>
        internal static string Warning_AlreadyRunning {
            get {
                return ResourceManager.GetString("Warning.AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher already running!.
        /// </summary>
        internal static string Warning_AlreadyRunningTitle {
            get {
                return ResourceManager.GetString("Warning.AlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is still some download or install active!
        ///Closing the Launcher now would damage the files or the game itself.
        ///Please try again, after the launcher finished its work!.
        /// </summary>
        internal static string Warning_CantStopNow {
            get {
                return ResourceManager.GetString("Warning.CantStopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadly, you cant close now!.
        /// </summary>
        internal static string Warning_CantStopNowTitle {
            get {
                return ResourceManager.GetString("Warning.CantStopNowTitle", resourceCulture);
            }
        }
    }
}
